spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:assess;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:h2:file:./assess;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

management:
  security:
    enabled: false

  endpoints:
    web:
      exposure:
        include: "*"


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html